<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Simon Thompson">
<meta name="author" content="Rohan Srinivasa Babu">
<meta name="dcterms.date" content="2026-08-15">

<title>Fatal Pedestrian and Cyclist Crash Risk Factors in Oregon</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="final-writeup_files/libs/clipboard/clipboard.min.js"></script>
<script src="final-writeup_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="final-writeup_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="final-writeup_files/libs/quarto-html/popper.min.js"></script>
<script src="final-writeup_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="final-writeup_files/libs/quarto-html/anchor.min.js"></script>
<link href="final-writeup_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="final-writeup_files/libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="final-writeup_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="final-writeup_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="final-writeup_files/libs/bootstrap/bootstrap-de9ea4695b5809f5b49b6072e50bb385.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul class="collapse">
  <li><a href="#title-team-and-affiliations" id="toc-title-team-and-affiliations" class="nav-link active" data-scroll-target="#title-team-and-affiliations"><span class="header-section-number">1</span> Title, Team, and Affiliations</a></li>
  <li><a href="#abstract" id="toc-abstract" class="nav-link" data-scroll-target="#abstract"><span class="header-section-number">2</span> Abstract</a></li>
  <li><a href="#introduction-problem-and-research-questions" id="toc-introduction-problem-and-research-questions" class="nav-link" data-scroll-target="#introduction-problem-and-research-questions"><span class="header-section-number">3</span> Introduction: Problem and Research Questions</a>
  <ul class="collapse">
  <li><a href="#problem-statement" id="toc-problem-statement" class="nav-link" data-scroll-target="#problem-statement"><span class="header-section-number">3.1</span> Problem statement</a></li>
  <li><a href="#research-questions" id="toc-research-questions" class="nav-link" data-scroll-target="#research-questions"><span class="header-section-number">3.2</span> Research questions</a></li>
  <li><a href="#changes-since-the-m1-proposal" id="toc-changes-since-the-m1-proposal" class="nav-link" data-scroll-target="#changes-since-the-m1-proposal"><span class="header-section-number">3.3</span> Changes since the M1 proposal</a></li>
  </ul></li>
  <li><a href="#impact-and-stakeholders" id="toc-impact-and-stakeholders" class="nav-link" data-scroll-target="#impact-and-stakeholders"><span class="header-section-number">4</span> Impact and Stakeholders</a></li>
  <li><a href="#related-work-and-background" id="toc-related-work-and-background" class="nav-link" data-scroll-target="#related-work-and-background"><span class="header-section-number">5</span> Related Work and Background</a></li>
  <li><a href="#data-and-data-engineering" id="toc-data-and-data-engineering" class="nav-link" data-scroll-target="#data-and-data-engineering"><span class="header-section-number">6</span> Data and Data Engineering</a>
  <ul class="collapse">
  <li><a href="#data-sources" id="toc-data-sources" class="nav-link" data-scroll-target="#data-sources"><span class="header-section-number">6.1</span> Data sources</a></li>
  <li><a href="#scope-and-unit-of-observation" id="toc-scope-and-unit-of-observation" class="nav-link" data-scroll-target="#scope-and-unit-of-observation"><span class="header-section-number">6.2</span> Scope and unit of observation</a></li>
  <li><a href="#relational-structure-and-keys" id="toc-relational-structure-and-keys" class="nav-link" data-scroll-target="#relational-structure-and-keys"><span class="header-section-number">6.3</span> Relational structure and keys</a></li>
  <li><a href="#reproducible-pipeline" id="toc-reproducible-pipeline" class="nav-link" data-scroll-target="#reproducible-pipeline"><span class="header-section-number">6.4</span> Reproducible pipeline</a></li>
  <li><a href="#data-quality-findings" id="toc-data-quality-findings" class="nav-link" data-scroll-target="#data-quality-findings"><span class="header-section-number">6.5</span> Data-quality findings</a></li>
  </ul></li>
  <li><a href="#ethics-and-responsible-use" id="toc-ethics-and-responsible-use" class="nav-link" data-scroll-target="#ethics-and-responsible-use"><span class="header-section-number">7</span> Ethics and Responsible Use</a>
  <ul class="collapse">
  <li><a href="#privacy-and-consent" id="toc-privacy-and-consent" class="nav-link" data-scroll-target="#privacy-and-consent"><span class="header-section-number">7.1</span> Privacy and consent</a></li>
  <li><a href="#scope-and-undercoverage" id="toc-scope-and-undercoverage" class="nav-link" data-scroll-target="#scope-and-undercoverage"><span class="header-section-number">7.2</span> Scope and undercoverage</a></li>
  <li><a href="#ecological-interpretation" id="toc-ecological-interpretation" class="nav-link" data-scroll-target="#ecological-interpretation"><span class="header-section-number">7.3</span> Ecological interpretation</a></li>
  <li><a href="#fairness-and-potential-harms" id="toc-fairness-and-potential-harms" class="nav-link" data-scroll-target="#fairness-and-potential-harms"><span class="header-section-number">7.4</span> Fairness and potential harms</a></li>
  <li><a href="#non-causal-framing" id="toc-non-causal-framing" class="nav-link" data-scroll-target="#non-causal-framing"><span class="header-section-number">7.5</span> Non-causal framing</a></li>
  </ul></li>
  <li><a href="#methods-and-evaluation" id="toc-methods-and-evaluation" class="nav-link" data-scroll-target="#methods-and-evaluation"><span class="header-section-number">8</span> Methods and Evaluation</a>
  <ul class="collapse">
  <li><a href="#analytical-design" id="toc-analytical-design" class="nav-link" data-scroll-target="#analytical-design"><span class="header-section-number">8.1</span> Analytical design</a></li>
  <li><a href="#spatial-clustering-with-dbscan" id="toc-spatial-clustering-with-dbscan" class="nav-link" data-scroll-target="#spatial-clustering-with-dbscan"><span class="header-section-number">8.2</span> Spatial clustering with DBSCAN</a></li>
  <li><a href="#infrastructure-profiling" id="toc-infrastructure-profiling" class="nav-link" data-scroll-target="#infrastructure-profiling"><span class="header-section-number">8.3</span> Infrastructure profiling</a></li>
  <li><a href="#tract-level-demographic-analysis" id="toc-tract-level-demographic-analysis" class="nav-link" data-scroll-target="#tract-level-demographic-analysis"><span class="header-section-number">8.4</span> Tract-level demographic analysis</a></li>
  <li><a href="#evaluation-strategy" id="toc-evaluation-strategy" class="nav-link" data-scroll-target="#evaluation-strategy"><span class="header-section-number">8.5</span> Evaluation strategy</a></li>
  </ul></li>
  <li><a href="#results-and-visualizations" id="toc-results-and-visualizations" class="nav-link" data-scroll-target="#results-and-visualizations"><span class="header-section-number">9</span> Results and Visualizations</a>
  <ul class="collapse">
  <li><a href="#statewide-spatial-pattern-and-hotspot-examples" id="toc-statewide-spatial-pattern-and-hotspot-examples" class="nav-link" data-scroll-target="#statewide-spatial-pattern-and-hotspot-examples"><span class="header-section-number">9.1</span> Statewide spatial pattern and hotspot examples</a></li>
  <li><a href="#infrastructure-profile-of-systemic-hotspots" id="toc-infrastructure-profile-of-systemic-hotspots" class="nav-link" data-scroll-target="#infrastructure-profile-of-systemic-hotspots"><span class="header-section-number">9.2</span> Infrastructure profile of systemic hotspots</a></li>
  <li><a href="#demographic-correlations" id="toc-demographic-correlations" class="nav-link" data-scroll-target="#demographic-correlations"><span class="header-section-number">9.3</span> Demographic correlations</a></li>
  </ul></li>
  <li><a href="#discussion-limitations-and-future-work" id="toc-discussion-limitations-and-future-work" class="nav-link" data-scroll-target="#discussion-limitations-and-future-work"><span class="header-section-number">10</span> Discussion, Limitations, and Future Work</a>
  <ul class="collapse">
  <li><a href="#interpretation" id="toc-interpretation" class="nav-link" data-scroll-target="#interpretation"><span class="header-section-number">10.1</span> Interpretation</a></li>
  <li><a href="#limitations" id="toc-limitations" class="nav-link" data-scroll-target="#limitations"><span class="header-section-number">10.2</span> Limitations</a></li>
  <li><a href="#future-work" id="toc-future-work" class="nav-link" data-scroll-target="#future-work"><span class="header-section-number">10.3</span> Future work</a></li>
  </ul></li>
  <li><a href="#conclusions-and-recommendations" id="toc-conclusions-and-recommendations" class="nav-link" data-scroll-target="#conclusions-and-recommendations"><span class="header-section-number">11</span> Conclusions and Recommendations</a></li>
  <li><a href="#reproducibility-and-references" id="toc-reproducibility-and-references" class="nav-link" data-scroll-target="#reproducibility-and-references"><span class="header-section-number">12</span> Reproducibility and References</a>
  <ul class="collapse">
  <li><a href="#repository-workflow" id="toc-repository-workflow" class="nav-link" data-scroll-target="#repository-workflow"><span class="header-section-number">12.1</span> Repository workflow</a></li>
  <li><a href="#environment-and-dependencies" id="toc-environment-and-dependencies" class="nav-link" data-scroll-target="#environment-and-dependencies"><span class="header-section-number">12.2</span> Environment and dependencies</a></li>
  <li><a href="#reproduce-the-write-up" id="toc-reproduce-the-write-up" class="nav-link" data-scroll-target="#reproduce-the-write-up"><span class="header-section-number">12.3</span> Reproduce the write-up</a></li>
  </ul></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references"><span class="header-section-number">13</span> References</a></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="../../final-writeup.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Fatal Pedestrian and Cyclist Crash Risk Factors in Oregon</h1>
<p class="subtitle lead">A Spatial Analysis (2015–2024)</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Authors</div>
    <div class="quarto-title-meta-contents">
             <p>Simon Thompson </p>
             <p>Rohan Srinivasa Babu </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">August 15, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="title-team-and-affiliations" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Title, Team, and Affiliations</h1>
<p><strong>Project title:</strong> <em>Fatal Pedestrian and Cyclist Crash Risk Factors in Oregon: A Spatial Analysis (2015–2024)</em></p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Team member</th>
<th>Project role</th>
<th>Email</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Simon Thompson</td>
<td>Owner Product Lead; data engineering and spatial analysis</td>
<td>sthompson2@willamette.edu</td>
</tr>
<tr class="even">
<td>Rohan Srinivasa Babu</td>
<td>Statistical analysis, interpretation, and communication</td>
<td>rsrinivasababu@willamette.edu</td>
</tr>
</tbody>
</table>
<p><strong>Peer Stakeholder Product Owners</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Peer stakeholder</th>
<th>Role</th>
<th>Email</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Aiyana Brown</td>
<td>Peer Stakeholder Product Owner</td>
<td>acbrown2@willamette.edu</td>
</tr>
<tr class="even">
<td>Amaya Supancich-McCord</td>
<td>Peer Stakeholder Product Owner</td>
<td>asupancichmccord@willamette.edu</td>
</tr>
<tr class="odd">
<td>Seira Ramchandani</td>
<td>Peer Stakeholder Product Owner</td>
<td>sramchandani@willamette.edu</td>
</tr>
</tbody>
</table>
<p><strong>Affiliation:</strong> DATA 510 Data Science Capstone, Willamette University, Summer 2026<br>
<strong>Repository:</strong> <a href="https://github.com/S1mT/data510-OregonPedSafety" class="uri">https://github.com/S1mT/data510-OregonPedSafety</a></p>
</section>
<section id="abstract" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Abstract</h1>
<p>Fatal pedestrian and cyclist crashes are not distributed evenly across Oregon. This project uses 2015–2024 records from the National Highway Traffic Safety Administration’s Fatality Analysis Reporting System (FARS), enriched with U.S. Census Bureau American Community Survey (ACS) data, to examine where fatal non-motorist crashes concentrate and which roadway, environmental, temporal, and community characteristics are associated with them. A reproducible two-stage data pipeline integrates five annual FARS tables, assigns crash coordinates to Oregon Census tracts, and appends tract-level demographic and commuting measures. The final dataset contains 1,049 fatal pedestrian and cyclist victim records representing 490 unique crashes. DBSCAN identified 15 candidate spatial clusters using a 0.1-mile neighborhood radius and at least three fatal-victim records; filtering to locations containing at least two distinct crash incidents produced 11 systemic hotspots containing 40 fatal-victim records across 32 unique incidents. These hotspots were disproportionately concentrated on arterial roads and two-way roads with continuous left-turn lanes. Among tracts represented in the crash data, fatal-crash rates were weakly but significantly associated with lower median income, higher Black population share, and higher transit/walking commute share. The results are descriptive rather than causal and are intended to help transportation agencies prioritize corridors and communities for closer local investigation, additional data collection, and targeted safety investment.</p>
</section>
<section id="introduction-problem-and-research-questions" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Introduction: Problem and Research Questions</h1>
<section id="problem-statement" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="problem-statement"><span class="header-section-number">3.1</span> Problem statement</h2>
<p>Pedestrians and cyclists are among the most physically vulnerable users of the transportation system. When a collision occurs, they have little protection from vehicle mass and speed. Fatal crashes may also reflect recurring patterns in road design, lighting, speed environment, location, and surrounding community conditions. Identifying those patterns can help transportation agencies move from reacting to individual crashes toward prioritizing locations for further safety investigation and investment.</p>
<p>FARS provides a standardized national census of police-reported motor-vehicle traffic crashes involving at least one fatality <span class="citation" data-cites="nhtsaFARS">(<a href="#ref-nhtsaFARS" role="doc-biblioref">National Highway Traffic Safety Administration 2026b</a>)</span>. This project focuses specifically on fatal pedestrian and cyclist crashes in Oregon between 2015 and 2024. The analysis combines crash circumstances, infrastructure variables, spatial clustering, and Census tract context to describe both where fatalities concentrate and what characteristics are common in those locations.</p>
</section>
<section id="research-questions" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="research-questions"><span class="header-section-number">3.2</span> Research questions</h2>
<p><strong>Primary research question:</strong> Which environmental, roadway, and temporal factors are most strongly associated with fatal pedestrian and cyclist crashes in Oregon between 2015 and 2024?</p>
<p><strong>Secondary research question:</strong> Are fatal pedestrian and cyclist crashes disproportionately concentrated in Oregon communities with particular demographic or socioeconomic characteristics between 2015 and 2024?</p>
</section>
<section id="changes-since-the-m1-proposal" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="changes-since-the-m1-proposal"><span class="header-section-number">3.3</span> Changes since the M1 proposal</h2>
<p>The original charter focused on the Salem area. After data acquisition and validation, the geographic scope was expanded to statewide Oregon. The statewide FARS extract offered a more complete and analytically useful sample while preserving the project’s transportation-safety purpose. The title was also revised to remove the phrase <em>predictive analysis</em>. A supervised predictive model was ultimately not included because the dataset contains only crashes involving at least one fatality and therefore lacks a defensible non-fatal or no-crash comparison group. Training a model to predict fatality from a fatal-only sample would create an ill-defined target and could produce misleading performance claims. The final analysis instead emphasizes spatial clustering, descriptive infrastructure profiling, and tract-level statistical associations.</p>
</section>
</section>
<section id="impact-and-stakeholders" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Impact and Stakeholders</h1>
<p><strong>Pedestrians and cyclists</strong> are the primary affected stakeholders because they bear the direct safety consequences of hazardous roadway conditions. The project does not assign individual responsibility for crashes; instead, it examines recurring system-level patterns that may indicate locations requiring closer review.</p>
<p><strong>The Oregon Department of Transportation (ODOT)</strong> is a potential user of the findings because it administers statewide transportation-safety programs and seeks to reduce crashes involving people walking and biking <span class="citation" data-cites="odotBikePed">(<a href="#ref-odotBikePed" role="doc-biblioref">Oregon Department of Transportation 2026</a>)</span>. Statewide hotspot and infrastructure patterns may help guide screening, data collection, and prioritization, but they should not replace site-specific engineering analysis.</p>
<p><strong>City and county transportation planners</strong> may use the results to identify corridors where local roadway geometry, traffic control, lighting, crossing design, or land-use context should be examined. The analysis is intended to narrow the field of locations for investigation rather than prescribe a single intervention.</p>
<p><strong>Public-health organizations and community advocates</strong> may use the findings to support injury-prevention and transportation-equity discussions. Because tract-level demographic variables describe neighborhoods rather than crash victims, the equity analysis must be interpreted carefully and should not be used to stigmatize communities.</p>
<p>The peer stakeholder group’s shared theme is data-driven prediction of community and urban outcomes. Their perspective encouraged the team to connect technical analysis to realistic policy uses, limitations, and equity implications rather than treating analytical output as an end in itself.</p>
</section>
<section id="related-work-and-background" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Related Work and Background</h1>
<p>FARS is maintained by NHTSA as a nationwide census of fatal motor-vehicle traffic crashes. It provides annual crash-, vehicle-, and person-level files as well as specialized pedestrian and bicyclist information <span class="citation" data-cites="nhtsaFARS nhtsaFARSManual">(<a href="#ref-nhtsaFARS" role="doc-biblioref">National Highway Traffic Safety Administration 2026b</a>, <a href="#ref-nhtsaFARSManual" role="doc-biblioref">2026a</a>)</span>. Because it includes only crashes meeting the fatality criterion, FARS is appropriate for studying the circumstances of fatal crashes but cannot independently estimate the probability that any roadway user, trip, or location will experience a crash.</p>
<p>Transportation-safety research frequently combines crash records with geographic analysis to identify high-density locations and recurring roadway conditions. DBSCAN is a density-based clustering algorithm designed to identify clusters of irregular shape while distinguishing isolated observations as noise <span class="citation" data-cites="ester1996">(<a href="#ref-ester1996" role="doc-biblioref">Ester et al. 1996</a>)</span>. These properties make it useful for exploratory hotspot detection because fatal crash locations do not necessarily form circular or administratively bounded groups.</p>
<p>The ACS provides annually released social, economic, housing, and demographic estimates, including five-year estimates for Census tracts <span class="citation" data-cites="censusACS5">(<a href="#ref-censusACS5" role="doc-biblioref">U.S. Census Bureau 2026</a>)</span>. This project uses tract-level ACS measures to add neighborhood context to fatal crash locations. The resulting variables should be interpreted as characteristics of the surrounding tract, not as attributes of individual victims.</p>
<p>Oregon’s pedestrian and bicycle planning framework emphasizes safety, equity, accessibility, connectivity, and strategic investment <span class="citation" data-cites="odot2016plan">(<a href="#ref-odot2016plan" role="doc-biblioref">Oregon Department of Transportation 2016</a>)</span>. This project contributes to that broader planning context by combining statewide fatal-crash records, localized hotspot identification, infrastructure profiling, and tract-level demographic analysis in one reproducible workflow.</p>
</section>
<section id="data-and-data-engineering" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Data and Data Engineering</h1>
<section id="data-sources" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="data-sources"><span class="header-section-number">6.1</span> Data sources</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Source</th>
<th>Role in the project</th>
<th>Coverage and access</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>NHTSA Fatality Analysis Reporting System (FARS)</td>
<td>Crash, person, pedestrian/bicyclist, vehicle, weather, temporal, roadway, and coordinate variables</td>
<td>Annual national CSV files, 2015–2024; U.S. government public data <span class="citation" data-cites="nhtsaFARS">(<a href="#ref-nhtsaFARS" role="doc-biblioref">National Highway Traffic Safety Administration 2026b</a>)</span></td>
</tr>
<tr class="even">
<td>U.S. Census Bureau TIGER/Line tract boundaries</td>
<td>Spatially assigns each valid crash coordinate to an Oregon Census tract</td>
<td>2020 Oregon Census tract shapefile</td>
</tr>
<tr class="odd">
<td>2022 ACS 5-year estimates</td>
<td>Median income, population, racial/ethnic composition, and transit/walking commute measures</td>
<td>Census API; tract-level estimates <span class="citation" data-cites="censusACS2022">(<a href="#ref-censusACS2022" role="doc-biblioref">U.S. Census Bureau 2022</a>)</span></td>
</tr>
</tbody>
</table>
</section>
<section id="scope-and-unit-of-observation" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="scope-and-unit-of-observation"><span class="header-section-number">6.2</span> Scope and unit of observation</h2>
<p>The final analysis-ready dataset contains <strong>1,049 fatal pedestrian and cyclist victim records</strong>, representing <strong>490 unique Oregon crashes</strong> from 2015 through 2024. It contains <strong>38 variables</strong> and no duplicate rows. The unit of observation is an individual fatal non-motorist victim, not a unique crash. Multiple victims can therefore share the same <code>ST_CASE</code> crash identifier.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Victim type</th>
<th style="text-align: right;">Records</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Pedestrian</td>
<td style="text-align: right;">881</td>
</tr>
<tr class="even">
<td>Bicyclist</td>
<td style="text-align: right;">124</td>
</tr>
<tr class="odd">
<td>Personal conveyance / other pedalcyclist</td>
<td style="text-align: right;">44</td>
</tr>
<tr class="even">
<td><strong>Total</strong></td>
<td style="text-align: right;"><strong>1,049</strong></td>
</tr>
</tbody>
</table>
</section>
<section id="relational-structure-and-keys" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="relational-structure-and-keys"><span class="header-section-number">6.3</span> Relational structure and keys</h2>
<p>The source data are highly normalized. The engineering pipeline uses the following identifiers:</p>
<ul>
<li><code>ST_CASE</code>: unique crash identifier;</li>
<li><code>VEH_NO</code>: vehicle identifier within a crash;</li>
<li><code>PER_NO</code>: person identifier within a crash;</li>
<li><code>STR_VEH</code>: striking-vehicle number recorded for the non-motorist;</li>
<li><code>GEOID</code>: Census tract identifier added during spatial enrichment.</li>
</ul>
<p>The raw FARS tables are joined in the following sequence:</p>
<ol type="1">
<li><code>person.csv</code> and <code>pbtype.csv</code> are inner-joined using <code>STATE</code>, <code>STATENAME</code>, <code>ST_CASE</code>, <code>VEH_NO</code>, and <code>PER_NO</code> to create the victim-level base.</li>
<li><code>accident.csv</code> is left-joined by <code>STATE</code>, <code>STATENAME</code>, and <code>ST_CASE</code> to append crash-level location, environmental, temporal, and roadway context.</li>
<li>Multiple weather records for the same crash are collapsed into a pipe-separated value and then left-joined by crash key.</li>
<li>The victim’s <code>STR_VEH</code> is matched to <code>vehicle.csv</code>’s <code>VEH_NO</code> within the same <code>ST_CASE</code> to retrieve speed-limit, traffic-control, and trafficway variables associated with the striking vehicle.</li>
</ol>
</section>
<section id="reproducible-pipeline" class="level2" data-number="6.4">
<h2 data-number="6.4" class="anchored" data-anchor-id="reproducible-pipeline"><span class="header-section-number">6.4</span> Reproducible pipeline</h2>
<p>The data pipeline has two stages. In Stage 1, <code>data/scripts/initial.py</code> reads annual national FARS files from <code>data/raw/</code>, standardizes column names, filters Oregon records using <code>STATE = 41</code>, writes annual Oregon-specific interim tables, performs the relational joins described above, concatenates all years, and exports <code>data/processed/FARSinfrastructure.csv</code>.</p>
<p>In Stage 2, <code>data/scripts/enrich.py</code> filters invalid placeholder coordinates, converts valid crash records to a GeoDataFrame, downloads Oregon Census tract boundaries, and performs a point-in-polygon spatial join. It then queries the 2022 ACS five-year API for income, population, race/ethnicity, transit, and walking-commute variables. Census suppression codes are converted to missing values, tract-level percentages are calculated, and the ACS data are joined by <code>GEOID</code> to create <code>data/processed/FARSmaster.csv</code>.</p>
<div id="fig-pipeline" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-pipeline-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/pipeline.png" class="img-fluid figure-img" style="width:55.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-pipeline-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Final two-stage data pipeline from raw FARS tables through infrastructure integration and Census/ACS enrichment.
</figcaption>
</figure>
</div>
</section>
<section id="data-quality-findings" class="level2" data-number="6.5">
<h2 data-number="6.5" class="anchored" data-anchor-id="data-quality-findings"><span class="header-section-number">6.5</span> Data-quality findings</h2>
<p>The project identified several important data-quality constraints.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Variable</th>
<th style="text-align: right;">Not reported</th>
<th style="text-align: right;">Share of records</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Traffic control device</td>
<td style="text-align: right;">593</td>
<td style="text-align: right;">57%</td>
</tr>
<tr class="even">
<td>Speed limit</td>
<td style="text-align: right;">248</td>
<td style="text-align: right;">24%</td>
</tr>
<tr class="odd">
<td>Weather</td>
<td style="text-align: right;">132</td>
<td style="text-align: right;">13%</td>
</tr>
</tbody>
</table>
<p>Many source-data gaps are represented by standardized labels such as <code>None / Unknown</code> or <code>Not Reported</code> rather than true null values. These labels are retained because they reflect information unavailable in the original records rather than a processing failure. The final dataset includes 863 urban records, 185 rural records, and one record without a reported urban/rural classification. Victim ages range from 1 to 95, with a mean of 48.9 and a median of 50.</p>
</section>
</section>
<section id="ethics-and-responsible-use" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> Ethics and Responsible Use</h1>
<section id="privacy-and-consent" class="level2" data-number="7.1">
<h2 data-number="7.1" class="anchored" data-anchor-id="privacy-and-consent"><span class="header-section-number">7.1</span> Privacy and consent</h2>
<p>The project uses public government records and does not contain direct personal identifiers, names, addresses, or protected health information. FARS represents victims through anonymous identifiers such as <code>ST_CASE</code> and <code>PER_NO</code>. Census measures are aggregated to the tract level and do not identify individual households.</p>
</section>
<section id="scope-and-undercoverage" class="level2" data-number="7.2">
<h2 data-number="7.2" class="anchored" data-anchor-id="scope-and-undercoverage"><span class="header-section-number">7.2</span> Scope and undercoverage</h2>
<p>FARS includes only crashes involving at least one fatality. The dataset therefore cannot describe all pedestrian and cyclist crashes, near misses, or underlying travel exposure. Findings should be framed as patterns among recorded fatal crashes rather than total pedestrian or cyclist risk.</p>
</section>
<section id="ecological-interpretation" class="level2" data-number="7.3">
<h2 data-number="7.3" class="anchored" data-anchor-id="ecological-interpretation"><span class="header-section-number">7.3</span> Ecological interpretation</h2>
<p>ACS variables describe the Census tract surrounding each crash location. They do not establish the income, race, ethnicity, or travel behavior of the victim. Interpreting tract-level associations as individual-level relationships would be an ecological fallacy.</p>
</section>
<section id="fairness-and-potential-harms" class="level2" data-number="7.4">
<h2 data-number="7.4" class="anchored" data-anchor-id="fairness-and-potential-harms"><span class="header-section-number">7.4</span> Fairness and potential harms</h2>
<p>Historical infrastructure investment, enforcement, reporting practices, and travel patterns may differ across communities. A map that labels a neighborhood as a hotspot could stigmatize residents or encourage enforcement-heavy responses without addressing roadway design. Results should therefore be used to support equitable investigation, community engagement, and infrastructure review rather than to assign blame.</p>
</section>
<section id="non-causal-framing" class="level2" data-number="7.5">
<h2 data-number="7.5" class="anchored" data-anchor-id="non-causal-framing"><span class="header-section-number">7.5</span> Non-causal framing</h2>
<p>The study is observational. DBSCAN identifies spatial concentration, feature summaries describe common conditions, and correlations measure linear association. None of these methods independently establish that a roadway or demographic feature caused a fatal crash. Exposure, traffic volume, land use, and other unmeasured factors may confound observed relationships.</p>
</section>
</section>
<section id="methods-and-evaluation" class="level1" data-number="8">
<h1 data-number="8"><span class="header-section-number">8</span> Methods and Evaluation</h1>
<section id="analytical-design" class="level2" data-number="8.1">
<h2 data-number="8.1" class="anchored" data-anchor-id="analytical-design"><span class="header-section-number">8.1</span> Analytical design</h2>
<p>The final analysis uses three complementary approaches:</p>
<ol type="1">
<li><strong>Spatial clustering</strong> to identify localized concentrations of fatal crashes;</li>
<li><strong>Infrastructure profiling</strong> to compare roadway conditions inside systemic hotspots with statewide fatal-crash records;</li>
<li><strong>Tract-level demographic analysis</strong> to examine relationships between fatal crash rates and community characteristics.</li>
</ol>
<p>The analysis does not include a supervised predictive model. Because every observation comes from a fatal crash, the dataset lacks a valid negative class or exposure denominator from which to model the probability of fatal-crash occurrence. A predictive model trained only on fatal cases would not answer the research question and could imply predictive validity that the available data do not support.</p>
</section>
<section id="spatial-clustering-with-dbscan" class="level2" data-number="8.2">
<h2 data-number="8.2" class="anchored" data-anchor-id="spatial-clustering-with-dbscan"><span class="header-section-number">8.2</span> Spatial clustering with DBSCAN</h2>
<p><code>data/scripts/DBSCAN.py</code> applies DBSCAN to latitude and longitude coordinates using the Haversine distance metric. The final specification uses a neighborhood radius of <strong>0.1 miles (approximately 161 meters)</strong> and <code>min_samples = 3</code>, meaning that at least three fatal-victim records must fall within the local neighborhood to form a candidate cluster. The poster rounded the radius to approximately 200 meters for presentation.</p>
<p>Because multiple victims may come from the same crash, candidate clusters were then passed to <code>data/scripts/hotspot_profiler.py</code> and filtered to retain only clusters containing <strong>at least two distinct <code>ST_CASE</code> crash incidents</strong>. This second step distinguishes repeated-location patterns from a single multi-fatality event. The combination produced <strong>15 candidate DBSCAN clusters</strong> and <strong>11 systemic hotspots</strong>.</p>
<p>Parameter sensitivity was examined around the final specification. Holding <code>min_samples = 3</code>, a 0.075-mile radius produced 8 systemic hotspots containing 26 fatal-victim records, the final 0.1-mile radius produced 11 hotspots containing 40 records, and a 0.125-mile radius produced 19 hotspots containing 67 records. At the final 0.1-mile radius, increasing <code>min_samples</code> from 3 to 4 reduced the result to 3 systemic hotspots containing 16 records. These checks show that the exact hotspot inventory is parameter-dependent; the chosen specification should therefore be interpreted as a screening rule for compact recurring locations rather than a uniquely correct partition of Oregon crash risk.</p>
<p>The complete systemic hotspot inventory is shown below. <code>Radius_Meters</code> is the maximum Haversine distance from each cluster centroid to its furthest included record, plus a 20-meter display buffer used by the mapping script.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 15%">
<col style="width: 21%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">Internal cluster ID</th>
<th style="text-align: right;">Unique crash incidents</th>
<th style="text-align: right;">Fatal-victim records</th>
<th>Years represented</th>
<th style="text-align: right;">Display radius (m)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">4</td>
<td>2016, 2017, 2018, 2024</td>
<td style="text-align: right;">163.1</td>
</tr>
<tr class="even">
<td style="text-align: right;">1</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">3</td>
<td>2015, 2019, 2023</td>
<td style="text-align: right;">123.6</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">3</td>
<td>2016, 2019, 2020</td>
<td style="text-align: right;">44.3</td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">3</td>
<td>2015, 2016</td>
<td style="text-align: right;">145.8</td>
</tr>
<tr class="odd">
<td style="text-align: right;">7</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">3</td>
<td>2017, 2020, 2021</td>
<td style="text-align: right;">97.5</td>
</tr>
<tr class="even">
<td style="text-align: right;">8</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">3</td>
<td>2017, 2018, 2022</td>
<td style="text-align: right;">36.4</td>
</tr>
<tr class="odd">
<td style="text-align: right;">9</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">3</td>
<td>2017, 2022, 2024</td>
<td style="text-align: right;">31.8</td>
</tr>
<tr class="even">
<td style="text-align: right;">10</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">3</td>
<td>2018, 2019, 2020</td>
<td style="text-align: right;">47.4</td>
</tr>
<tr class="odd">
<td style="text-align: right;">11</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">3</td>
<td>2019, 2022</td>
<td style="text-align: right;">91.1</td>
</tr>
<tr class="even">
<td style="text-align: right;">12</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">7</td>
<td>2021, 2022</td>
<td style="text-align: right;">140.2</td>
</tr>
<tr class="odd">
<td style="text-align: right;">0</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">5</td>
<td>2015, 2020</td>
<td style="text-align: right;">81.6</td>
</tr>
</tbody>
</table>
<p>Across these 11 hotspots there are <strong>40 fatal-victim records representing 32 unique crash incidents</strong>, or <strong>3.8% of the 1,049 fatal-victim records</strong> in the final dataset.</p>
</section>
<section id="infrastructure-profiling" class="level2" data-number="8.3">
<h2 data-number="8.3" class="anchored" data-anchor-id="infrastructure-profiling"><span class="header-section-number">8.3</span> Infrastructure profiling</h2>
<p>For each systemic hotspot, <code>data/scripts/hotspot_profiler.py</code> records the most common value for roadway and environmental variables including urban/rural classification, functional system, trafficway type, posted speed limit, intersection type, traffic control, lighting, weather, and pedestrian position. The pooled systemic-hotspot records are then compared with all 1,049 statewide fatal-victim records.</p>
<p>The comparison is descriptive. It identifies roadway conditions that are more common within the selected hotspots than in the statewide fatal-crash dataset, but it does not estimate independent causal effects or adjust for roadway mileage, traffic volume, or pedestrian/cyclist exposure.</p>
</section>
<section id="tract-level-demographic-analysis" class="level2" data-number="8.4">
<h2 data-number="8.4" class="anchored" data-anchor-id="tract-level-demographic-analysis"><span class="header-section-number">8.4</span> Tract-level demographic analysis</h2>
<p><code>data/scripts/DemographicAnalysis.py</code> aggregates <code>FARSmaster.csv</code> by Census tract. The numerator is the number of <strong>unique fatal crash incidents (<code>ST_CASE</code>)</strong> in each represented tract, and the denominator is tract population:</p>
<p><span class="math display">\[
\text{Fatal crash rate per 10,000 residents}
=
\frac{\text{Unique fatal crash incidents}}{\text{Tract population}}
\times 10{,}000
\]</span></p>
<p>The analysis table contains 491 Census tracts represented in the crash data; 489 tracts have complete values across the five demographic predictors and are used in the Pearson correlation analysis. The predictors are median household income, percentage White, percentage Black, percentage Hispanic, and percentage of commuters who walk or use public transit.</p>
<p>For visual comparisons, median income is divided into quartiles using the observed tract distribution: Q1 = $23,765–$57,399; Q2 = $57,553–$70,572; Q3 = $70,594–$85,806; and Q4 = $85,950–$193,846. Black population share is divided into tertiles: Low = 0–0.154%, Medium = 0.158–1.410%, and High = 1.423–27.109%. These categories are descriptive quantile groupings, not policy thresholds.</p>
<p>Five Pearson correlations were tested. The report presents two-sided p-values and 95% confidence intervals. As a conservative multiple-testing check, a Bonferroni-adjusted significance level of 0.01 (<code>0.05 / 5</code>) was also considered.</p>
</section>
<section id="evaluation-strategy" class="level2" data-number="8.5">
<h2 data-number="8.5" class="anchored" data-anchor-id="evaluation-strategy"><span class="header-section-number">8.5</span> Evaluation strategy</h2>
<p>The project evaluates results through internal consistency rather than predictive accuracy. Spatial outputs are checked for plausible geographic concentration and compared with the underlying incident records. Hotspot profiles are compared against statewide feature prevalence so that common statewide conditions are not automatically treated as hotspot-specific. Demographic findings are reported with effect sizes, p-values, confidence intervals, and a multiple-testing check. Across all analyses, interpretation is constrained to association and screening rather than causal attribution.</p>
</section>
</section>
<section id="results-and-visualizations" class="level1" data-number="9">
<h1 data-number="9"><span class="header-section-number">9</span> Results and Visualizations</h1>
<section id="statewide-spatial-pattern-and-hotspot-examples" class="level2" data-number="9.1">
<h2 data-number="9.1" class="anchored" data-anchor-id="statewide-spatial-pattern-and-hotspot-examples"><span class="header-section-number">9.1</span> Statewide spatial pattern and hotspot examples</h2>
<p>DBSCAN produced 15 candidate clusters under the final 0.1-mile, three-record specification. After requiring at least two distinct crash incidents, 11 systemic hotspots remained. These hotspots contain 40 fatal-victim records across 32 unique crash incidents. Although this is a small share of the statewide victim records, the clusters identify compact locations where fatal incidents recur across different years rather than one-time multi-victim events.</p>
<div id="fig-statewide-hotspots" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-statewide-hotspots-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/statewide_systemic_hotspots.png" class="img-fluid figure-img" style="width:75.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-statewide-hotspots-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Systemic DBSCAN hotspots in the final Oregon dataset. The colored points show fatal-victim records belonging to the 11 retained systemic hotspots; other fatal-victim records are shown in the background.
</figcaption>
</figure>
</div>
<p>Two Portland-area examples illustrate the recurrence pattern. The Southeast 82nd Avenue hotspot contains four unique crash incidents and four fatalities occurring in 2016, 2017, 2018, and 2024 within an approximately 163-meter display radius. The Southeast 181st Avenue hotspot contains three unique incidents and three fatalities occurring in 2015, 2019, and 2023 within an approximately 124-meter display radius. Their separation across multiple years is why the poster described them as recurring or reactivated locations rather than isolated events.</p>
<div class="quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-82nd" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-82nd-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/se_82nd_hotspot.jpg" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-82nd-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Southeast 82nd Avenue systemic hotspot: four distinct fatal crash incidents across 2016, 2017, 2018, and 2024.
</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-181st" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-181st-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/se_181st_hotspot.jpg" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-181st-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Southeast 181st Avenue systemic hotspot: three distinct fatal crash incidents across 2015, 2019, and 2023.
</figcaption>
</figure>
</div>
</div>
</div>
</div>
</section>
<section id="infrastructure-profile-of-systemic-hotspots" class="level2" data-number="9.2">
<h2 data-number="9.2" class="anchored" data-anchor-id="infrastructure-profile-of-systemic-hotspots"><span class="header-section-number">9.2</span> Infrastructure profile of systemic hotspots</h2>
<p>The pooled hotspot profile shows several conditions that differ from the statewide fatal-crash dataset. <strong>Arterial roads</strong> account for 92.5% of systemic-hotspot records compared with 60.4% statewide. <strong>Two-way roads with a continuous left-turn lane</strong> account for 50.0% of hotspot records compared with 23.7% statewide. <strong>Dark but lighted conditions</strong> also appear more often within hotspots (57.5%) than statewide (32.8%).</p>
<p>By contrast, <strong>non-intersection locations</strong> account for 57.5% of hotspot records but 70.6% statewide. This is an important qualification: non-intersection crashes are common in the fatal-crash dataset generally and are not uniquely elevated within the identified hotspots.</p>
<div id="fig-infrastructure" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-infrastructure-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/infrastructure_comparison.png" class="img-fluid figure-img" style="width:78.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-infrastructure-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: Selected roadway and environmental conditions among systemic-hotspot records compared with all statewide fatal-victim records. Percentages describe record prevalence, not exposure-adjusted risk.
</figcaption>
</figure>
</div>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Feature</th>
<th style="text-align: right;">Systemic hotspots</th>
<th style="text-align: right;">Statewide</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Arterial road</td>
<td style="text-align: right;">92.5%</td>
<td style="text-align: right;">60.4%</td>
</tr>
<tr class="even">
<td>Not at an intersection</td>
<td style="text-align: right;">57.5%</td>
<td style="text-align: right;">70.6%</td>
</tr>
<tr class="odd">
<td>Two-way road with continuous left-turn lane</td>
<td style="text-align: right;">50.0%</td>
<td style="text-align: right;">23.7%</td>
</tr>
<tr class="even">
<td>Dark – lighted</td>
<td style="text-align: right;">57.5%</td>
<td style="text-align: right;">32.8%</td>
</tr>
</tbody>
</table>
<p>The differences are most useful as screening signals. Arterial classification and continuous center left-turn lanes stand out as recurring features of the retained hotspots, but without roadway mileage and travel exposure the analysis cannot determine whether those road types are intrinsically more dangerous or simply carry more traffic and pedestrian activity.</p>
</section>
<section id="demographic-correlations" class="level2" data-number="9.3">
<h2 data-number="9.3" class="anchored" data-anchor-id="demographic-correlations"><span class="header-section-number">9.3</span> Demographic correlations</h2>
<p>The final tract-level Pearson results are shown below.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 17%">
<col style="width: 23%">
<col style="width: 17%">
<col style="width: 23%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th>Tract characteristic</th>
<th style="text-align: right;">r</th>
<th>95% CI</th>
<th style="text-align: right;">p-value</th>
<th>Interpretation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Percent Black</td>
<td style="text-align: right;">0.184</td>
<td>[0.097, 0.269]</td>
<td style="text-align: right;">&lt;0.001</td>
<td>Weak positive</td>
</tr>
<tr class="even">
<td>Percent transit/walking commuters</td>
<td style="text-align: right;">0.143</td>
<td>[0.055, 0.229]</td>
<td style="text-align: right;">0.0015</td>
<td>Weak positive</td>
</tr>
<tr class="odd">
<td>Median income</td>
<td style="text-align: right;">-0.136</td>
<td>[-0.222, -0.047]</td>
<td style="text-align: right;">0.0027</td>
<td>Weak negative</td>
</tr>
<tr class="even">
<td>Percent White</td>
<td style="text-align: right;">-0.077</td>
<td>[-0.164, 0.012]</td>
<td style="text-align: right;">0.0898</td>
<td>Not significant</td>
</tr>
<tr class="odd">
<td>Percent Hispanic</td>
<td style="text-align: right;">0.008</td>
<td>[-0.081, 0.096]</td>
<td style="text-align: right;">0.8675</td>
<td>Not significant</td>
</tr>
</tbody>
</table>
<p>With five tests, the Bonferroni-adjusted threshold is <code>p &lt; 0.01</code>. The associations with Black population share, transit/walking commute share, and median income remain below this conservative threshold; White and Hispanic population shares do not. All three statistically significant coefficients are nevertheless small in magnitude, so statistical significance should not be confused with a large substantive effect.</p>
<p>The grouped income comparison is directionally consistent with the correlation result. Average fatal crash rates decline from <strong>6.19 per 10,000 residents</strong> in the lowest-income quartile to <strong>4.19 per 10,000</strong> in the highest-income quartile. The middle quartiles average 5.33 and 4.98 per 10,000, respectively.</p>
<div id="fig-income" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-income-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/income_chart.png" class="img-fluid figure-img" style="width:68.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-income-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6: Average fatal pedestrian/cyclist crash rate per 10,000 residents among crash-represented Census tracts, grouped by median-income quartile. Quartile cut points are defined in the Methods section.
</figcaption>
</figure>
</div>
<p>The Black population-share chart shows average rates of <strong>4.77</strong>, <strong>4.96</strong>, and <strong>5.94</strong> per 10,000 residents across the low, medium, and high tertiles, respectively. This pattern is consistent with the positive correlation, but it remains a neighborhood-level association and does not identify the race of individual crash victims or establish a causal mechanism.</p>
<div id="fig-black" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-black-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/black_pop_chart.png" class="img-fluid figure-img" style="width:68.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-black-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7: Average fatal crash rate per 10,000 residents among crash-represented Census tracts, grouped into tertiles of Black population share. Tertile cut points are defined in the Methods section.
</figcaption>
</figure>
</div>
</section>
</section>
<section id="discussion-limitations-and-future-work" class="level1" data-number="10">
<h1 data-number="10"><span class="header-section-number">10</span> Discussion, Limitations, and Future Work</h1>
<section id="interpretation" class="level2" data-number="10.1">
<h2 data-number="10.1" class="anchored" data-anchor-id="interpretation"><span class="header-section-number">10.1</span> Interpretation</h2>
<p>The final results support a consistent descriptive story. Fatal pedestrian and cyclist crashes are geographically dispersed across Oregon, but a subset recur in compact locations across multiple years. Eleven systemic hotspots remain after separating repeated crash locations from candidate DBSCAN clusters that could be driven by a single multi-fatality incident. Within those hotspots, arterial classification and continuous center left-turn lanes are substantially more prevalent than in the statewide fatal-crash dataset, while dark-but-lighted conditions are also more common.</p>
<p>The results do <strong>not</strong> support the simpler claim that every common hotspot feature is overrepresented. Non-intersection locations, for example, are common within hotspots but even more common statewide. This comparison illustrates why the statewide baseline is necessary: raw frequency within hotspots alone cannot distinguish a hotspot-specific pattern from a condition that is already common among fatal crashes generally.</p>
<p>The demographic analysis also provides evidence of neighborhood-level disparities, but the relationships are weak. Lower median income is associated with a higher fatal crash rate, while Black population share and transit/walking commute share are positively associated with the rate. These relationships remain statistically significant under a conservative Bonferroni check, yet their small effect sizes and the observational design make them better suited to prioritizing further investigation than to drawing causal conclusions.</p>
<p>Taken together, the spatial, infrastructure, and demographic results point toward a screening framework: identify recurring fatal-crash locations, characterize the roadway environments around them, and incorporate neighborhood context when deciding where deeper local analysis and safety investment may be warranted.</p>
</section>
<section id="limitations" class="level2" data-number="10.2">
<h2 data-number="10.2" class="anchored" data-anchor-id="limitations"><span class="header-section-number">10.2</span> Limitations</h2>
<p><strong>Fatal-only outcome.</strong> FARS excludes non-fatal crashes and locations with no reported fatal crash. The project therefore characterizes fatal-crash patterns rather than estimating the probability that a person, trip, or roadway segment will experience a crash.</p>
<p><strong>Lack of exposure denominators.</strong> The dataset does not contain pedestrian counts, cyclist counts, roadway mileage, or vehicle miles traveled. A location or tract may record more fatal crashes partly because more people travel through it.</p>
<p><strong>Crash-represented tract universe.</strong> The demographic table is constructed from <code>FARSmaster.csv</code>, so it contains tracts represented by at least one fatal crash record rather than every Oregon tract, including zero-crash tracts. The correlation results should therefore be interpreted within this observed-crash tract universe.</p>
<p><strong>Missing roadway information.</strong> Traffic-control and speed-limit variables contain substantial <code>Not Reported</code> values. This reduces confidence in feature-prevalence estimates and may introduce systematic reporting bias.</p>
<p><strong>Victim-versus-crash unit.</strong> The spatial dataset contains one row per fatal victim. Multi-victim crashes can therefore create candidate density clusters. The systemic-hotspot filter mitigates this by requiring at least two unique <code>ST_CASE</code> incidents, but pooled feature percentages still describe victim records rather than equal-weighted crash events.</p>
<p><strong>Spatial precision and parameter dependence.</strong> Coordinate errors and geocoding precision can affect cluster membership. The sensitivity checks also demonstrate that changing the DBSCAN radius or minimum-sample threshold changes the number of detected hotspots. The 0.1-mile specification is a practical screening choice rather than a uniquely correct spatial scale.</p>
<p><strong>ACS timing and uncertainty.</strong> The project applies 2022 ACS five-year tract estimates to crashes spanning 2015–2024. Neighborhood conditions may have changed during the study period, and ACS sampling uncertainty is not propagated into the correlation analysis.</p>
<p><strong>Ecological fallacy and confounding.</strong> Tract demographics cannot be attributed to individual victims. Income, race/ethnicity, commute patterns, urban density, roadway design, transit availability, and exposure may be interrelated. The observed correlations do not isolate the effect of any one factor.</p>
</section>
<section id="future-work" class="level2" data-number="10.3">
<h2 data-number="10.3" class="anchored" data-anchor-id="future-work"><span class="header-section-number">10.3</span> Future work</h2>
<p>The strongest next step is to add comparison and exposure data rather than increasing model complexity on the current fatal-only sample. Future work should incorporate non-fatal pedestrian and cyclist crashes, pedestrian and bicycle counts, vehicle volumes, roadway mileage, posted and operating speeds, lane counts, crossing infrastructure, and historical roadway changes. These additions would allow the project to distinguish high use from unusually high risk and would support stronger regression or predictive designs.</p>
<p>Spatial work could also be extended by testing hotspot stability across a wider parameter grid, applying road-network-constrained clustering rather than straight-line distance alone, and comparing hotspot locations with local engineering inventories. For the equity analysis, including all Oregon Census tracts—including zero-fatal-crash tracts—and incorporating ACS uncertainty would provide a stronger population-level comparison.</p>
</section>
</section>
<section id="conclusions-and-recommendations" class="level1" data-number="11">
<h1 data-number="11"><span class="header-section-number">11</span> Conclusions and Recommendations</h1>
<p>Fatal pedestrian and cyclist crashes in Oregon show meaningful spatial concentration rather than a uniform statewide pattern. The final analysis identifies <strong>11 systemic hotspots</strong> containing repeated crash incidents across multiple years. These hotspots are disproportionately represented on arterial roads and two-way roads with continuous left-turn lanes, while the demographic analysis finds weak but statistically significant associations between fatal crash rates and lower median income, higher Black population share, and higher transit/walking commute share.</p>
<p>For ODOT and local transportation agencies, the immediate value of this work is <strong>screening and prioritization</strong> rather than causal diagnosis. Three recommendations follow from the evidence:</p>
<ol type="1">
<li><strong>Conduct corridor-level safety reviews of recurring arterial hotspots.</strong> Reviews should examine speed environment, crossing distance, lighting, lane configuration, center-turn-lane design, transit access, and pedestrian/cyclist desire lines.</li>
<li><strong>Collect exposure and infrastructure data before selecting interventions.</strong> Pedestrian, cyclist, and vehicle volumes are necessary to distinguish high use from unusually high risk and to support stronger comparative analysis.</li>
<li><strong>Apply an equity-centered review process.</strong> Neighborhood-level demographic signals should prompt deeper investigation, community engagement, and infrastructure review—not assumptions about individual victims or enforcement-heavy responses.</li>
</ol>
<p>The central takeaway is that statewide fatal-crash data can identify recurring locations and roadway conditions that deserve closer attention, but responsible action requires combining these screening signals with local engineering evidence, exposure measures, and community knowledge.</p>
</section>
<section id="reproducibility-and-references" class="level1" data-number="12">
<h1 data-number="12"><span class="header-section-number">12</span> Reproducibility and References</h1>
<section id="repository-workflow" class="level2" data-number="12.1">
<h2 data-number="12.1" class="anchored" data-anchor-id="repository-workflow"><span class="header-section-number">12.1</span> Repository workflow</h2>
<p>The final repository separates processing, analysis, and outputs. Core scripts are located under <code>data/scripts/</code>:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Script</th>
<th>Purpose</th>
<th>Main output</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>initial.py</code></td>
<td>Extract Oregon records and integrate FARS relational tables</td>
<td><code>data/processed/FARSinfrastructure.csv</code></td>
</tr>
<tr class="even">
<td><code>enrich.py</code></td>
<td>Spatial join to Census tracts and ACS enrichment</td>
<td><code>data/processed/FARSmaster.csv</code></td>
</tr>
<tr class="odd">
<td><code>DBSCAN.py</code></td>
<td>Final Haversine DBSCAN clustering</td>
<td><code>data/processed/FARSclusters.csv</code></td>
</tr>
<tr class="even">
<td><code>hotspot_profiler.py</code></td>
<td>Systemic-hotspot filtering and feature profiles</td>
<td><code>systemic_hotspots_incidents.csv</code>, <code>systemic_hotspots_profile.csv</code></td>
</tr>
<tr class="odd">
<td><code>interactive_map_generator.py</code></td>
<td>Interactive hotspot maps</td>
<td>HTML maps in <code>data/processed/</code></td>
</tr>
<tr class="even">
<td><code>DemographicAnalysis.py</code></td>
<td>Tract aggregation, correlations, and grouped charts</td>
<td>demographic statistics and figures</td>
</tr>
</tbody>
</table>
<p>From the repository root, the core analytical sequence is:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="ex">python</span> data/scripts/initial.py</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="ex">python</span> data/scripts/enrich.py</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="ex">python</span> data/scripts/DBSCAN.py</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="ex">python</span> data/scripts/hotspot_profiler.py</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="ex">python</span> data/scripts/interactive_map_generator.py</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="ex">python</span> data/scripts/DemographicAnalysis.py</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>The first stage requires the annual FARS national folders for 2015–2024 under <code>data/raw/</code>. <code>enrich.py</code> also requires a Census API key. Before public portfolio release, the key should be supplied through an environment variable or local configuration rather than committed directly in source code.</p>
</section>
<section id="environment-and-dependencies" class="level2" data-number="12.2">
<h2 data-number="12.2" class="anchored" data-anchor-id="environment-and-dependencies"><span class="header-section-number">12.2</span> Environment and dependencies</h2>
<p>A pinned <code>requirements.txt</code> is provided at the repository root. Install the Python environment with:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="ex">python</span> <span class="at">-m</span> pip install <span class="at">-r</span> requirements.txt</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>The pinned environment includes pandas, GeoPandas, Shapely, NumPy, scikit-learn, SciPy, Folium, matplotlib, seaborn, requests, and Jupyter. Quarto is additionally required to render this report.</p>
</section>
<section id="reproduce-the-write-up" class="level2" data-number="12.3">
<h2 data-number="12.3" class="anchored" data-anchor-id="reproduce-the-write-up"><span class="header-section-number">12.3</span> Reproduce the write-up</h2>
<p>From the repository root:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="ex">quarto</span> render deliverables/M5-final-poster-and-writeup/final-writeup.qmd</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>The report embeds final poster figures where they already existed and adds static summary figures generated from the final processed data. The interactive HTML hotspot maps remain available under <code>data/processed/</code> for location-level inspection.</p>
</section>
</section>
<section id="references" class="level1" data-number="13">
<h1 data-number="13"><span class="header-section-number">13</span> References</h1>
<div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-ester1996" class="csl-entry" role="listitem">
Ester, Martin, Hans-Peter Kriegel, Jörg Sander, and Xiaowei Xu. 1996. <span>“A Density-Based Algorithm for Discovering Clusters in Large Spatial Databases with Noise.”</span> <em>Proceedings of the Second International Conference on Knowledge Discovery and Data Mining</em>, 226–31. <a href="https://cdn.aaai.org/KDD/1996/KDD96-037.pdf">https://cdn.aaai.org/KDD/1996/KDD96-037.pdf</a>.
</div>
<div id="ref-nhtsaFARSManual" class="csl-entry" role="listitem">
National Highway Traffic Safety Administration. 2026a. <em>Fatality Analysis Reporting System Analytical User’s Manual, 1975–2024</em>. U.S. Department of Transportation. <a href="https://crashstats.nhtsa.dot.gov/Api/Public/ViewPublication/813794">https://crashstats.nhtsa.dot.gov/Api/Public/ViewPublication/813794</a>.
</div>
<div id="ref-nhtsaFARS" class="csl-entry" role="listitem">
National Highway Traffic Safety Administration. 2026b. <em>Fatality Analysis Reporting System (FARS)</em>. <a href="https://www.nhtsa.gov/research-data/fatality-analysis-reporting-system-fars">https://www.nhtsa.gov/research-data/fatality-analysis-reporting-system-fars</a>.
</div>
<div id="ref-odot2016plan" class="csl-entry" role="listitem">
Oregon Department of Transportation. 2016. <em>Oregon Bicycle and Pedestrian Plan</em>. Oregon Department of Transportation. <a href="https://www.oregon.gov/ODOT/Planning/Documents/OBPP.pdf">https://www.oregon.gov/ODOT/Planning/Documents/OBPP.pdf</a>.
</div>
<div id="ref-odotBikePed" class="csl-entry" role="listitem">
Oregon Department of Transportation. 2026. <em>Pedestrian and Bicycle Program</em>. <a href="https://www.oregon.gov/odot/programs/pages/bikeped.aspx">https://www.oregon.gov/odot/programs/pages/bikeped.aspx</a>.
</div>
<div id="ref-censusACS2022" class="csl-entry" role="listitem">
U.S. Census Bureau. 2022. <em>2022 American Community Survey 5-Year API</em>. <a href="https://api.census.gov/data/2022/acs/acs5">https://api.census.gov/data/2022/acs/acs5</a>.
</div>
<div id="ref-censusACS5" class="csl-entry" role="listitem">
U.S. Census Bureau. 2026. <em>American Community Survey 5-Year Data</em>. <a href="https://www.census.gov/data/developers/data-sets/acs-5year.html">https://www.census.gov/data/developers/data-sets/acs-5year.html</a>.
</div>
</div>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>